- .github/workflows/ci.sh
- .github/workflows/ci.yml
- test/polkit/polkitidentitytest.c
- test/polkitbackend/meson.build
- test/polkitbackend/polkitbackendjsauthoritytest-wrapper.py
Introduce a GH Actions job that builds & tests polkit in three
"categories":
1) Build with various optimization levels & other build-time options
(both clang & gcc)
2) Build & run the unit tests (both clang & gcc)
3) Build & run the unit tests with Address Sanitizer and
Undefined Behavior Sanitizer (only gcc for now)
There's a couple of outstanding issues that should be taken care of in
the near future:
- get rid of the gazillion of warnings during compilation so we can
build with -Werror (--werror)
- fix build with clang >= 17
- make test-polkitbackendjsauthority work under ASan
> ci: run build & unit tests in GH Actions

- .github/workflows/codeql.yml
Analyze the polkit code using CodeQL [0], to discover potential vulnerabilities before they reach the main branch.
[0] https://codeql.github.com/docs/
---
Once this is merged, it'll do the initial scan and populate the "Code Scanning" tab in the "Security" repo section, like this:
(This tab is accessible only to the repo maintainers, given the sensitive nature of some of the alerts.)
Each alert then shows further information and steps how to remediate it:
I enabled the extended CodeQL queries as well (as I think polkit would benefit from them, given its security nature). However, the extended checks are more prone to false positives, so if that's something you'll find annoying, it can be easily toned back down to only high-precision checks.
The results of the initial scan will be in the …
> ci: introduce CodeQL

- src/polkitagent/polkitagenttextlistener.c
Calling abort() in polkitagenttextlistener.c causes coredumps as it abruptly ends pkttyagent program, but we can finish gracefully.
> pkttyagent: EOF in password causes coredump

- test/mocklibc/src/netgroup-debug.c
- test/mocklibc/src/netgroup.c
This fixes build error with GCC >= 14 and clang >= 17, failing on:
```
../subprojects/mocklibc-1.0/src/netgroup-debug.c:25:3: error: implicit declaration of function ‘print_indent’ [-Wimplicit-function-declaration]
25 |   print_indent(stream, indent);
|   ^~~~~~~~~~~~
```
Issue reported 11 years ago to (dead) upstream: https://code.google.com/archive/p/mocklibc/issues/3.
Closes: #6
> mocklibc: move the print_indent function to the file where it is used

- src/polkitbackend/polkitbackendsessionmonitor-systemd.c
Currently, the polkitbackendsessionmonitor watches all notifications from sd-login-monitor. This causes waking polkit even four+ times on every login/logout and starting a train of action re-verification several times for each instantiated PolkitAuthority (e.g. applets on gnome-shell panel that utilize PolkitPermission).
This is not necessary, because polkit only needs to watch for sessions that change status from active to online and vice-versa (to maintain security for actions that have is_active defined). This still doesn't resolve the problem completely, but at least halves the impact on system resources.
On a …
> Sessions monitor should watch only changes in sessions

- data/org.freedesktop.PolicyKit1.Authority.xml
- src/polkit/polkitauthority.c
- src/polkit/polkitpermission.c
- src/polkitbackend/polkitbackendauthority.c
- src/polkitbackend/polkitbackendinteractiveauthority.c
Currently, every time the systemd-logind monitor sends a notification about change in sessions, all instances of PolkitPermission (and probably other classes using PolkitAuthority) send CheckAuthorization to the daemon even though their session is not affected. This hogs the cpu needlessly, because ALL programs/applets in ALL instances for ALL users send CheckAuthorization, making each such request even repeated. This PR adds recognition of a change in sessions, adds it to the "Changed" dbus signal as a parameter, and on the client side of polkit (i.e. PolkitAuthority) enables to react accordingly. This enables PolkitPermission to assess whether the session change affects just the objects in affected sessions.
[Please be more …
> Only instances affected by sessions change should call for CheckAuthorization

- .github/workflows/codeql.yml
So we get newer meson, which is required since 60673b8:
> ci: bump the CodeQL GH Actions worker to Ubuntu Noble

- src/programs/pkexec.c
This is a resubmitted patch by Olivier Duchateau from the previous GitLab hosting. Closes https://github.com/polkit-org/polkit/issues/356
> Add similar feature of Linux's prctl() for FreeBSD, using procctl(2)

- .packit/polkit.spec
- data/polkit-tmpfiles.conf
- meson.build
tmpfiles.d will automatically create the /etc/polkit-1/rules.d directory (and any non-existing directories on the path). After reboot, the directory contents will remain unchanged, and after removing the directory & rebooting, an empty directory will be created.
tmpfiles.d in fedora: https://docs.fedoraproject.org/en-US/packaging-guidelines/Tmpfiles.d/
tmpfiles.d manpage: https://www.freedesktop.org/software/systemd/man/latest/tmpfiles.d.html
> tmpfiles.d: install and use systemd-tmpfiles.d mechanism to .packit conf

- data/org.freedesktop.PolicyKit1.Authority.xml
- docs/polkit/docbook-interface-org.freedesktop.PolicyKit1.Authority.xml
- src/polkit/polkitcheckauthorizationflags.h
- src/polkitbackend/polkitbackendinteractiveauthority.c
Currently if the subject has uid 0 a shortcut is taken and authorization is immediately granted, without checking against policies and rules. Add a flag that allows skipping this shortcut.
uid 0 can of course alter polkit's behaviour directly, so this is not so much a security feature, but more useful as a safety feature, so that when an action is disabled it cannot be accidentally performed by root, unless they really mean it and bypass polkit.
I intend to make use of this in logind, in the inhibitor functionality, to ensure even root has to drop an inhibitor lock before taking an action.
> Add new flag to check root user too in ChcekAuthorization

- src/programs/pkexec.c
Reading `/etc/shells` file directly has the effect that comments are parsed as well. If a user sets environment variable `SHELL` to a value which matches one of these comments, it is passed through pkexec.
The shadow tools would not allow such a login shell, so be as strict as shadow when it comes to parsing `/etc/shell`.
Proof of Concept:
1. Add a comment to `/etc/shells` (if it does not already exist)
```
/bin/sh
/bin/bash
```
2. For sake of completeness, try to add a comment line through latest `chsh` of shadow:
```
$ chsh -s '# Begin /etc/shells'
chsh: # Begin /etc/shells is an invalid shell
```
3. Run `pkexec` with `SHELL` being one of the comment lines
```
$ SHELL="# Begin /etc/shells" pkexec
```
You can see:
```
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ==== …
```
> pkexec: enforce absolute shell paths

- .github/workflows/codeql.yml
There's no `matrix.ref`, only `github.ref`. Use that to make sure we don't kill workflow jobs from other PRs.
Followup for b3a3a256.
Resolves: #467
> ci: actually use the current reference in group ID

- meson.build
Removes a workaround, as the issue appears to be fixed since meson 0.63.0 (https://github.com/mesonbuild/meson/pull/10170)
> Move -std=c99 to meson default_options

- data/meson.build
- meson.build
Session tracking build options are about whether logind or other APIs
are used in the polkit code, at compilation and linking time.
units, sysusers and tmpfiles files have nothing to do with code changes
or APIs, they simply install config files, that can just be ignored if
they are not needed. Use pkg-config if available, but otherwise have
a hard-coded fallback with the well-known defaults.
This also fixes another bug,  'systemdsystemunitdir' is specified as
an option the systemd_dep variable is not defined, but the sysusers.d
directory lookup uses it, causing a build failure:
```
dh_auto_configure -- \
-Dexamples=false \
-Dintrospection=true \
-Dman=true \
-Dsystemdsystemunitdir=/usr/lib/systemd/system \
-Dtests=true \
-Dgtk_doc=true -Dsession_tracking=libsystemd-login
cd …
```
> meson: decouple session tracking mechanism from unit and sysusers

- data/polkit.service.in
- src/polkitbackend/polkitbackendauthority.c
- src/polkitbackend/polkitbackendauthority.h
- src/polkitbackend/polkitbackendcommon.c
- src/polkitbackend/polkitbackendduktapeauthority.c
- src/polkitbackend/polkitbackendinteractiveauthority.c
- src/polkitbackend/polkitbackendjsauthority.cpp
- src/polkitbackend/polkitd.c
Alternative to https://github.com/polkit-org/polkit/pull/477
> Add --log-level and LogControl1 support

- src/polkitbackend/polkitbackendduktapeauthority.c
#482 added a new argument to `polkit_backend_authority_log` but it wasn't added to the calls inside of the `HAVE_PTHREAD_CONDATTR_SETCLOCK` ifdef.
Otherwise the polkit package on alpine linux edge fails to build: https://gitlab.alpinelinux.org/sertonix/aports/-/jobs/1479902
```
../src/polkitbackend/polkitbackendduktapeauthority.c:776:35: error: passing argument 2 of 'polkit_backend_authority_log' makes integer from pointer without a cast [-Wint-conversion]
776 |                                   "Error setting condition variable attributes: %s",
| …
```
> Fix missing arguments with HAVE_PTHREAD_CONDATTR_SETCLOCK

- meson_options.txt
- src/polkitbackend/50-default.rules.in
- src/polkitbackend/meson.build
Add -Dprivileged_group that can be used to override the default of 'wheel', which is set in 50-default.rules. In Debian and derivatives, the privileged group is 'sudo', 'wheel' does not exist.
We have been carrying an out-of-tree patch in Debian to change the hard-coded group from wheel to sudo. This allows us to simply configure it via meson. Default is still the same.
> Add meson option for privileged group

- test/integration/pkexec/expect/SIGTRAP-on-EOF.exp
- test/integration/pkexec/expect/basic-auth.exp
- test/integration/pkexec/main.fmf
- test/integration/pkexec/test.sh
Add a couple of tests for pkexec utilizing Tcl's Expect, which allows us
to handle pkexec's interactivity in a reasonable-ish way.
Note: the '# notsecret' comment in the test is necessary, otherwise I
was getting flooded by RH's infosec about leaked passwords.
> test: add a couple of tests for pkexec

- meson.build
- src/polkitbackend/meson.build
I removed feature test macro definitions (i.e `_GNU_SOURCE`/`_XOPEN_SOURCE`) from polkitbackend because `_GNU_SOURCE` is already defined in the root meson.build.
Explicitly defining `_XOPEN_SOURCE` is redundant because `_GNU_SOURCE` implies `_XOPEN_SOURCE 700` (according to the comments in glibc's `features.h`)
Depends on #454
> Fix duplicate feature test macros

- test/wrapper.py
On some build systems, like Debian's, the tests do not have permissions to create new namespaces, so skip gracefully in that case
Follow-up for 8e17f09c770bc2efd5deb40ba2b6032d40603578
> test: skip if the namespace cannot be set up due to permissions or if python3 is too old

- src/polkitbackend/polkitbackendduktapeauthority.c
Align polkit with other services (e.g. [sysctl](https://man7.org/linux/man-pages/man8/sysctl.8.html)) and search for rules in all the traditional config sources in the usual order.
This adjustment ensures that the failure to open the rules directory is logged as a debug message rather than an error, reducing noise in the logs.
> backendduktape: Add searched rule directories and adjust the LOG_LEVEL

- meson.build
- meson_options.txt
The Yocto/Openembedded project uses PAM integration with `common-*` files instead of the default `system-*`.
This PR adds  a `openembedded` `os_type` in meson (using the `suse` code path) to match that.
In Openembedded, same as Suse/Solaris: PAM files are common-*:
* PAM_FILE_INCLUDE_AUTH: common-auth
* PAM_FILE_INCLUDE_ACCOUNT: common-account
* PAM_FILE_INCLUDE_PASSWORD: common-password
* PAM_FILE_INCLUDE_SESSION: common-session
Since the automated OS detection will not work in a cross-compiler case. Polkit is built using the default `system-*` files and OE need to maintain a patch to change to `common-*`.
> meson: Support "openembedded" OS for PAM configuration

- data/meson.build
Those files are only required when the daemon is in use, and because of their hard-coded paths when libsystemd isn't available, it fails to build in Flatpak.
> build: Don't install daemon files when building libs only

- src/polkitbackend/polkitbackendcommon.c
It is only defined for service type units, and an error is returned otherwise, so check before querying.
Follow-up for a23d9ce375dcbc64aade92f3e082182b993c1169
> jsauthority: do not query NoNewPrivileges for non-service units

- docs/man/polkit.xml
- src/polkitbackend/polkitbackendduktapeauthority.c
The standard directory is /usr/share/polkit-1/rules.d, not /usr/lib/polkit-1/rules.d, so maintain consistency by searching in /usr/local/share/polkit-1/rules.d instead of /usr/local/lib/polkit-1/rules.d.
Follow-up for https://github.com/polkit-org/polkit/pull/498
> backendduktape: search for rules in /usr/local/share rather than /usr/local/lib and update docs

- data/polkit.service.in
- src/polkitbackend/polkitbackendactionpool.c
- src/polkitbackend/polkitbackendactionpool.h
- src/polkitbackend/polkitbackendinteractiveauthority.c
- src/polkitbackend/polkitbackendinteractiveauthority.h
- src/polkitbackend/polkitd.c
- test/integration/systemd/test.sh
Add support for active reloading of config files via SIGHUP. Also integrate with sd_notify when building with libsystemd, and set Type=notify-reload in the systemd unit, so that a 'systemctl reload polkit' works out of the box.
This is especially useful when booting a read-only image, which gets configuration updates via overmounting with another read-only image.
> Implement configuration reloading on SIGHUP and sd_notify support

- meson.build
- src/polkit/polkitenumtypes.c.template
- src/polkit/polkitidentity.c
- src/polkit/polkitimplicitauthorization.h
- src/polkit/polkitpermission.c
- src/polkit/polkitsubject.c
- src/polkitagent/polkitagentenumtypes.c.template
- src/polkitagent/polkitagenthelperprivate.c
- src/polkitagent/polkitagenthelperprivate.h
- src/polkitagent/polkitagentsession.c
- src/polkitbackend/polkitbackendactionlookup.c
- src/polkitbackend/polkitbackendauthority.c
- src/polkitbackend/polkitbackendduktapeauthority.c
- src/polkitbackend/polkitbackendinteractiveauthority.c
- src/polkitbackend/polkitbackendsessionmonitor-systemd.c
- src/programs/pkcheck.c
The only ones left are those about the deprecated glib async functions, but there's quite a few of them
> Fix various compiler warnings

- meson.build
- meson_options.txt
- src/polkitbackend/polkitbackendactionpool.c
Disabled by default. Will be used in Debian/Ubuntu and derivatives,
where this patch has been carried out-of-tree for ~15 years.
Fixes https://github.com/polkit-org/polkit/issues/35
> Add meson option to use gettext for translations in .policy files

- meson.build
meson doesn't automatically add all project arguments to configure checks -- nor incrementally the inline value of all configuration_data entries.
But that meant it was missing -D_GNU_SOURCE, as well as a define added to config.h itself. As a result, this check failed to detect the necessary function definition and failed to link.
```
Command line: `gcc-14 /var/tmp/portage/sys-auth/polkit-125/work/polkit-125-build/meson-private/tmpj0ih4pm4/testfile.c -o /var/tmp/portage/sys-auth/polkit-125/work/polkit-125-build/meson-private/tmpj0ih4pm4/output.obj -c -pipe -march=native -fstack-protector-all -O2 -fdiagnostics-color=always -frecord-gcc-switches -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -Wformat -Werror=format-security -Werror=implicit-function-declaration …
```
> meson: correctly test for setnetgrent return type

- src/polkitbackend/polkitbackendauthority.c
After a long discussion, the polkit team decided to revert the implementation of LogControl1 in polkit for the following reasons:
1. The authentication/authorization part of changing LogLevel needs to be implemented. Without it, any user can change log level via busctl (https://github.com/polkit-org/polkit/issues/507)
2. https://github.com/polkit-org/polkit/issues/506  
After all these issues are addressed, integration of the protocol can be later reconsidered.
LogControl1 is not widely used so far, therefore no major damage will be caused by postponing the integration of the protocol within polkit.
This reverts commit 79d84d0dd0dd7d16c616555acf8cd14862d02baf.
> Revert "Implement LogControl1 protocol for dynamic log level changes"

- src/polkitbackend/polkitbackendauthority.c
Re-commit of https://github.com/polkit-org/polkit/commit/79d84d0dd0dd7d16c616555acf8cd14862d02baf with additional authorization check.
Setting log level via dbus api is now restricted to root only and setting log target is disabled completely.
Fixes #506 and #507
> Logcontrol re-integration

- src/polkit/polkitsystembusname.c
- src/polkitbackend/polkitbackendactionpool.c
- src/polkitbackend/polkitd.c
While trying to break polkit using dfuzzer I couldn't make ASan/LSan
report _any_ memory leaks no matter how obvious they were. After a lot
of tinkering I managed to get the reports only when calling
`__lsan_do_recoverable_leak_check()` explicitly, which told me that the
shutdown `__lsan_do_leak_check() `is somehow getting skipped.
Turns out that polkitd does a "proper" shutdown on `SIGINT` (with which
ASan/LSan worked as expected), but not for `SIGTERM`. Fixing this, by
stopping the even loop even on SIGTERM, makes ASan/LSan happy (except
for the couple of memory leaks that were unfortunately hidden by this
behavior).
---
This PR together with #520 should be, for now, hopefully enough to let me introduce dfuzzer into polkit's test suite and address …
> Shutdown polkitd properly on SIGTERM

- .github/workflows/ci.sh
- meson.build
- src/polkitbackend/polkitbackendactionpool.c
- src/polkitbackend/polkitbackendauthority.c
- src/polkitbackend/polkitd.c
- src/programs/pkexec.c
There's still a bunch of warnings caused by `-Wdeprecated-declarations`, but these can be easily suppressed by `-Dc_args=-Wno-deprecated-declarations` for now.
This PR also tweaks the CI jobs to build with `-Werror`, so we should be able to catch these kind of issues a bit earlier in the future.
> Fix a couple of compilation warnings when building with clang

- .packit.yaml
Let's do a Packit build on "commit" events as well, which automagically enables Packit's OpenScanHub integration [0].
Since OSH runs only on x86_64 Fedora Rawhide builds, let's limit the scope for the "commit" event adequately; we still do the usual builds across all supported Fedora releases (and architectures) in PRs.
The OSH integration is still in its experimental stage, but there's a plan to add SARIF support and integrate it into GitHub's UI (see [1]), which should make it quite useful.
[0] https://packit.dev/posts/openscanhub-prototype
[1] https://github.com/packit/dashboard/issues/441
---
Note: this won't have any effect until it's merged, as OSH needs at least one build from the default (main) branch to have something to compare against.
> ci: run Packit on commit events as well

- test/integration/dfuzzer/main.fmf
- test/integration/dfuzzer/test.sh
- test/integration/util.sh
Let's run dfuzzer to fuzz polkit's own D-Bus interface to catch issues
like [0][1][2] early.
The test implementation is a _bit_ convoluted, caused by the fact that
we have to rebuild polkit with Address and Undefined sanitizers to make
dfuzzer considerably more effective. This also involves running the just
built polkit in a lightweight container so we don't mess with the
already installed polkit (which could affect tests running after this
one that don't expect sanitized polkit). All this extra code can be
potentially dropped once we're able to do multiple Packit builds in one
PR (currently in an RFC stage).
Resolves: https://github.com/polkit-org/polkit/issues/515
[0] https://github.com/polkit-org/polkit/issues/506
[1] https://github.com/polkit-org/polkit/commit/b709b693346712bf8e8d8e8c7 …
> test: run dfuzzer against Polkit's D-Bus interface

- .github/workflows/coverity.sh
- .github/workflows/coverity.yml
_Note: I created this PR's branch intentionally directly in the upstream repo, so it has access to the repo secrets with the Coverity token, as PRs from forks can't do that._
Let's reintroduce regular Coverity builds. Since there's a pretty strict rate limit [0], do one nightly build each day, and upload it to Coverity for analysis. The results can be then found in the project dashboard [1].
[0] https://scan.coverity.com/faq#frequency
[1] https://scan.coverity.com/projects/polkit?tab=overview
Resolves: #517
> ci: do nightly polkit builds & submit them to Coverity

- src/polkitbackend/polkitbackendsessionmonitor-systemd.c
fix: need goto out after g_set_error
goto out needs to be executed after g_set_error , otherwise the assertion will be triggered in g_assert (process != NULL);
> fix: need goto out after g_set_error

- src/polkitbackend/polkitd.c
On non-systemd systems if the user is changed manually, polkitd will also change directory. The homedir of the user might not be set correctly, so just change to /.
This is a no-op on systemd systems, as the user is set in the unit file, so this code never runs.
> Explicitly use chdir("/") instead of relying on ~user being set properly

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
This PR should make the _Build & Test_ and _CodeQL_  CI jobs green again by:
- not using `sudo` in the Fedora test container, since we already have root anyway
- disabling automatic dependency installation during CodeQL's autobuild, since it started pulling in `sccache` which breaks code tracing during the (auto)build
> A couple of fixes for recent CI fails

- src/polkitbackend/meson.build
polkit-126 could not be built from source with elogind session service due to wrong dependencies in meson.build.
Author: @markhindley
> meson: fix unused dependency, fixes elogind FTBFS

- .github/workflows/ci.yml
Fix-up (https://github.com/polkit-org/polkit/commit/e0c6725e378d01865e5967db5d7ca596e237d34f).
> CI: Drop mozjs-devel from test dependencies

- src/polkitbackend/polkitbackendcommon.c
- src/polkitbackend/polkitbackendduktapeauthority.c
- src/polkitbackend/polkitbackendinteractiveauthority.c
- src/polkitbackend/polkitd.c
Increasing the priority of "Error opening rules directory" and decreasing the priority of e.g. "Finished loading" makes it easier for users to spot important messages at a glance.
> Change several log levels from NOTICE to INFO/WARNING

- .github/workflows/codeql.yml
- meson.build
Split from #454 as requested.
This is a minor change that requires meson >= 1.4.0, which isn't available in Fedora 39.
F39 becomes EOL on 2024-11-12.
> Dont hardcode path to config.h

- .github/workflows/codeql.yml
- .github/workflows/coverity.yml
Since it also runs on Ubuntu 24.04 which doesn't have new-enough meson.
Follow-up for 810b5dd863dbbb0a19c3613a1f5dd55c2e8ac886.
---
(Note: this is intentionally _not_ opened from a fork branch, so I can test the Coverity job indeed works as it needs access to repo tokens)
> ci: install newer meson for the Coverity job as well

- src/polkitagent/polkitagenthelper-pam.c
Before clearing the environment variables, save the language environment variable first, and then set it again after clearing the environment variables to solve the problem that the PAM messages are not translated.
> reset lang before clear env

- src/programs/pkexec.c
- test/integration/pkexec/test.sh
This changes the pkexec path that is compared from the original supplied path to the path resolved by realpath(3).
That means that "/bin/something" might now be matched as "/usr/bin/something", a review of your
<annotate key="org.freedesktop.policykit.exec.path">
actions might be in order.
Fixes: polkit-org/polkit#194
See also: systemd/systemd#34714
- This might cause backwards incompatibility issues.
- And that also has security implications. Although I think for the better.
> pkexec: Use realpath when comparing org.freedesktop.policykit.exec.path

- src/programs/pkexec.c
Disruptions between glibc and musl-(not-)predefined feature-test macros led to a decision to remove a check for POSIX standards older than 17 years. It makes no sense to test the existence of a macro that we explicitly define in meson.build either (shall we test for _GNU_SOURCE).
> Fix musl compilation error on Alpine

- test/integration/pkexec/test.sh
The second test tried to strace a setuid binary as an unprivileged user
which will never work, but the fact was hidden by missing strace on the
test machine. Let's rewrite the tests to fix this, and check a couple
more cases.
Follow-up for 9aa43e089d870a8ee695e625237c5b731b250678.
> test: rewrite tests for realpath() shenanigans 

- data/meson.build
- data/polkit-tmpfiles.conf
- data/polkit-tmpfiles.conf.in
Follow up to <https://github.com/polkit-org/polkit/pull/442#issuecomment-2692493869>.
- Make tmpfiles respect configured polkit group name
- Document the security implications for tmpfiles.d entry
We allow changing the polkit daemon user through the `-Dpolkitd_user` Meson option.
When this is used, the tmpfiles.d config will refer to a non-existent group.
For example, NixOS builds polkit with `-Dpolkitd_user=polkituser`.
Let’s substitute the `polkitd_user` value into the config.
We do not have a separate option for the group name since, by convention,
the group name matches the user name. This is also enforced by our `sysusers.d` config:
https://www.freedesktop.org/software/systemd/man/latest/sysusers.d.html#u
Quoting from <https://www.github.com/polkit-org/polkit/pull/442#issuecomment-269 …
> Make tmpfiles respect configured group name and document security implications

- data/polkit-agent-helper@.service.in
- src/polkitagent/polkitagenthelper-pam.c
Wrong password/timeout/cancelled authentication makes helper service failed, sending systemd state to degraded. This is linked to a specific pam event in helper source and can be perceived as a correct finish of the program on failed user interaction.
> Degraded state after wrong/cancelled auth

- src/polkit/polkitunixprocess.c
- src/polkit/polkitunixprocess.h
- src/polkitbackend/polkitbackendinteractiveauthority.c
sudo keeps a record of authenticated processes via either the controlling TTY (default) or the parent process id.
Implement the same caching behaviour, but stricter: if a process is authenticated for auth_keep, do not expunge it when it exits if it was tracked via PID FD (to make it safe against reuse attacks).
Then, if another process comes along, skip re-auth and allow it if it shared the same UID, parent process id, cgroup id and controlling terminal (and all processes are newer than the controlling terminal ctime). PID FDs must be used all the way through, otherwise there's no caching.
This is much stricter than sudo, as all conditions must be met. But it still allows to fulfill the main use case, which is to run multiple commands on the same terminal without being asked for the …
> auth_keep: do not ask for reauth if new process shares same UID/parent/cgroup/tty

- src/programs/pkexec.c
Various tools (including some in systemd) want to slightly change behaviour in case they detect they are invoked in a sudo or sudo-like context (for example disable certain security-sensitive interfaces). They currently mostly check $USER_UID to detect this situation, which will work for at least the sudo, run0, sudo-rs implementation of a privilege elevation tool. It doesn't work for pkexec however.
Let's change this, and for compatibility with sudo simply set the these two env vars too. This would increase compatibility for everyone in a simple, generic way.
Yes, it would be great if the env var would be more generically named than $SUDO_something, but I think at this point it shouldn't really matter, it's just a string.
Fixes: #561
> pkexec: also se $SUDO_UID/$SUDO_GID for compat with sudo

- src/polkitbackend/polkitbackendactionpool.c
XML .policy files with nesting deeper more than `PARSER_MAX_DEPTH` cause polkit to crash. It requires auth'ed user to put such file in monitored directories though.
Reported by Med Maatallah. Many thanks!
> Nested .policy files cause xml parsing overflow leading to crash

- src/polkitbackend/polkitbackendcommon.c
In version 0.117, the patch https://github.com/polkit-org/polkit/commit/8638ec5cd534dcc616b68e5b0744c493c0c71dc9 was merged to fix the issue of "zombie not reaped when js spawned process timed out." However, in version 121, the patch https://github.com/polkit-org/polkit/commit/c7fc4e1b61f0fd82fc697c19c604af7e9fb291a2 reverted the previous fix, causing the issue of "Leaking zombie child processes" to resurface.
> polkitd: fix zombie not reaped when js spawned process timed out
